# Setup
name:           Timsski
markdown:       kramdown

# Permalink
permalink:      /blog/:year/:month/:day/:title

# Assets
sass:
  sass_dir:     css
  style:        :compressed

theme: jekyll-theme-minimal